monster:
  id: 100
  name: "牛魔王~~"
  age: 500
  isMarried: true
  birth: 2000/10/10
  #对象
  #  car: {name: 宝马, price: 200000} #行内格式
  car: #换行格式
    name: 宝马~
    price: 300000
  #数组
  #  skill: [芭蕉扇, 牛魔拳] #行内格式
  skill:
    - 芭蕉扇~
    - 牛魔拳~
  #  hobby: [喝酒, 吃肉] #行内格式
  hobby:
    - 喝酒~
    - 吃肉~
  #map-属于对象
  #  wife: {no1: 玉面狐狸, no2: 铁扇公主} #行内风格
  wife:
    no1: 玉面狐狸~
    no2: 铁扇公主~
  #  salaries: [10000,20000] #行内风格
  salaries:
    - 10000
    - 20000
  cars: #因为cars k-v v是list<Car> 所以我们使用换行风格
    group1:
      - {name: 奔驰, price: 300000}
      - name: 保时捷
        price: 400000
    group2:
      - {name: 奔驰~, price: 100000}
      - name: 保时捷~
        price: 500000

#请求静态资源的路径改变方法 localhost:8080/static/xxx 改变请求网址
spring:
  mvc:
    static-path-pattern: /static/**
    view:
      suffix: .html
      prefix: /static/ #这里是需要注意 prefix需要和当前的static-path-pattern一致
#      等于是拼接了 /static/xxx.html

#    启用过滤器 前后端不分离用的
#    hiddenmethod:
#      filter:
#        enabled: true
  # 改变静态资源的路径
  web:
    resources:
      static-locations: ["classpath:/mystatic/","classpath:/static/","classpath:/public/","classpath:/resources/","classpath:/META-INF/resources/"]



